locations = set([
    'waterloo',
    'toronto',
    'mississauga',
    'kitchener',
    'fairview',
    'pearson',
    'scarborough',
    'brampton',
    'markham',
    'north york',
    'london',
    'ottawa',
    'vaughan',
    'hamilton',
    'oakville',
    'etobicoke',
    'kingston',
    'guelph',
    'newmarket',
    'thornhill',
    'bayview',
])
